### ISSUE TITLE
Upgrade vue-next to the latest one

### ISSUE THREAD

**Issue by msaelices** [rigor789/nativescript-vue-next#12]
As `vue-next` is in alpha state, it's changing a lot. IMHO we should update the `vue-next` dependency and fix our binging for breaking changes happened in `vue-next`. 

Posible breaking changes:

https://github.com/vuejs/vue-next/commit/ca5f39ee3501a1d9cacdb74108318c15ee7c0abb
https://github.com/vuejs/vue-next/commit/8f9afdff643af6ba0df5df88cd57732c0b484775
https://github.com/vuejs/vue-next/commit/966d7b5487e320e955d858fba76e89fb42e9d6eb
COMPLETE

**Tasks:**

- [ ] See the `BREAKING CHANGES` in the git history and complete the list
- [ ] Upgrade the NPM dependency
- [ ] Fix the probably broken code
